salario = float (input("salario atual: "))
if salario <=280:
	R = salario+(salario atual*(20/100))
	print("salario atual: {salario}")
	print("percentual aplicado: 20%")
	print("valor do almento: {salario*(20/100)}")
	print("salario com reajuste: {R}")
elif salario >=280 and salario <700:
	print("salario atual: {salario}")
	print("percentual aplicado: 15%")
	print("valor do almento: {salario*(15/100)}")
	R = salario+(salario*(15/100))
	print("salario com reajuste: {R}")
elif salario >700 and <1500:
	print("salario atual: {salario}")
	print("percentual aplicado: 10%")
	print("valor do almento: {salario*(10/100)}")
	R = salario+(salario*(10/100))
	print("salario com reajuste: {R}")
elif salario >=1500 and:
	print("salario atual: {salario}")
	print("percentual aplicado: 5%")
	print("valor do almento: {salario*(5/100)}")
	R = salario+(salario*(5/100))
	print("salario com reajuste: {R}")